## 新包对应新的sheet 示例：只需要全部替换ledger即可
codeGenerator:
    # 业务配置
    # 新包需要修改
    functionName: ledger
    # 新包需要修改
    functionDesc: 机构C5-客户模块基础微服务
    methodName: commissionDistributionDetails
    methodDesc: 账本-分仓佣金-佣金分配明细
    procedureName: PCX_GMKHST_YJFPMX
    # 新包需要修改
    interfaceIndex: 2
    pageEnabled: true
    isReturnResult: true
    testEnabled: true
    # 新包需要修改
    isCreateFile: false
    # 根路径
    protoSrcPath: D:\IdeaProjects\apexsoft\htzq\jgcrm-ams\ams-protocol\src\main\proto
    clientSrcPath: D:\IdeaProjects\apexsoft\htzq\jgcrm-ams\ams-client-org-customer\src\main\java
    serverSrcPath: D:\IdeaProjects\apexsoft\htzq\jgcrm-ams\ams-server-org-customer\src\main\java
    mapperXmlSrcPath: D:\IdeaProjects\apexsoft\htzq\jgcrm-ams\ams-server-org-customer\src\main\resources\mybatis\oracle\jgcrm
    serverTestSrcPath: D:\IdeaProjects\apexsoft\htzq\jgcrm-ams\ams-server-org-customer\src\test\java
    serverTestDataSrcPath: D:\IdeaProjects\apexsoft\htzq\jgcrm-ams\ams-server-org-customer\src\main\resources
    # 默认设置
    # 新包需要修改
    defaultPackageNamePrefix: com.apexsoft.crm.ledger
    whiteRegExp: czr
    # 其他设置
    # proto
    protoPackageName: ip.base.customer
    # 新包需要修改
    protoName: ledger
    rpcRegExp: .*Service\s+.*
    # 服务名
    serviceName: customer
